name: Bug
description: Report a bug
labels:
  - bug
body:
  - id: context
    type: textarea
    attributes:
      label: Context
      description: Give some context as to what the bug is.
      placeholder: When I tried to ... it ...
    validations:
      required: true
  - id: steps
    type: textarea
    attributes:
      label: Steps to reproduce
      description: List the steps to reproduce.
      placeholder: |
        1. ...
        2. ...
        3. ...
        4. ...
      validations:
        required: true
  - id: expected-results
    type: textarea
    attributes:
      label: Expected results
      description: Detail what was expected to happen.
    validations:
      required: true
  - id: actual-results
    type: textarea
    attributes:
      label: Actual results
      description: Detail what actually happened.
    validations:
      required: true